version: '3'
services:
  postgresql:
    build:
      context: '.'
      dockerfile: './Dockerfile'
    command: 'postgres -c config_file="/etc/postgresql.conf"'
    container_name: 'postgresql11'
    image: 'postgresql11:latest'
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
      - './conf/postgresql.conf:/etc/postgresql.conf'
volumes:
  pgdata:
    driver: 'local'
