version: '3'
services:
  postgresql:
    build: '.'
    container_name: 'postgresql11'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
      - './conf/postgresql.conf:/etc/postgresql.conf'
    ports:
      - '5432:5432'
    command: 'postgres -c config_file="/etc/postgresql.conf"'
volumes:
  pgdata:
    driver: 'local'
