version: "3"
services:
  postgresql_9_6:
    build:
      context: "."
      dockerfile: "./Dockerfile"
    command: 'postgres -c config_file="/etc/postgresql.conf"'
    container_name: "postgresql_9_6"
    image: "postgresql_9_6"
    ports:
      - "5432:5432"
    volumes:
      - "pgdata_9_6:/var/lib/postgresql/data"
      - "./conf/postgresql.conf:/etc/postgresql.conf"
volumes:
  pgdata_9_6:
    driver: "local"
